import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import {
  buildClaudeInstructions,
  buildCopilotInstructions,
  buildVsCodeCopilotAgent,
  syncGlobalAgentInstructions,
  syncAgentInstructions,
  syncLocalAgentInstructions,
  syncVsCodeCopilotAgent,
  upsertManagedMarkdownSection,
} from "../../src/infra/tooling/agent-instruction-sync.ts";

const AGENTS_SOURCE = `# Faro Path Author Agent

Use MCP first.
`;

const SKILL_SOURCE = `---
name: faro-author-paths
---

# Faro Author Paths

Use faro.upsertPath.
`;

test("buildClaudeInstructions embeds both source documents", () => {
  const content = buildClaudeInstructions({
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  assert.match(content, /generated by Faro/);
  assert.match(content, /Embedded AGENTS\.md/);
  assert.match(content, /Embedded SKILL\.md/);
  assert.match(content, /Use MCP first\./);
  assert.match(content, /Use faro\.upsertPath\./);
});

test("buildCopilotInstructions produces a concise repository instruction file", () => {
  const content = buildCopilotInstructions({
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  assert.match(content, /Faro Agent Instructions/);
  assert.match(content, /faro\.listPaths/);
  assert.match(content, /faro\.upsertPath/);
  assert.match(content, /AGENTS\.md remains the source of truth/);
});

test("buildVsCodeCopilotAgent produces a custom agent definition with Faro MCP tools", () => {
  const content = buildVsCodeCopilotAgent({
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  assert.match(content, /^---/);
  assert.match(content, /name: Faro Path Author/);
  assert.match(content, /tools: \['faro\.local\/\*'\]/);
  assert.match(content, /Use the Faro MCP tools to author or revise one temporary comprehension path\./);
  assert.match(content, /Use MCP first\./);
  assert.match(content, /Use faro\.upsertPath\./);
});

test("syncLocalAgentInstructions upserts only workspace-scoped artifacts", async () => {
  const sandboxRoot = await mkdtemp(path.join(tmpdir(), "faro-agent-sync-local-"));
  const workspaceRoot = path.join(sandboxRoot, "workspace");
  const codexHome = path.join(sandboxRoot, ".codex");

  await syncLocalAgentInstructions({
    workspaceRoot,
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  const claude = await readFile(path.join(workspaceRoot, "CLAUDE.md"), "utf8");
  const copilot = await readFile(
    path.join(workspaceRoot, ".github", "copilot-instructions.md"),
    "utf8",
  );
  const copilotAgent = await readFile(
    path.join(workspaceRoot, ".github", "agents", "faro-path-author.agent.md"),
    "utf8",
  );

  assert.match(claude, /Embedded AGENTS\.md/);
  assert.match(copilot, /Faro Agent Instructions/);
  assert.match(copilotAgent, /name: Faro Path Author/);
  await assert.rejects(
    readFile(path.join(codexHome, "skills", "faro-author-paths", "SKILL.md"), "utf8"),
  );
});

test("syncGlobalAgentInstructions upserts only the global Codex skill", async () => {
  const sandboxRoot = await mkdtemp(path.join(tmpdir(), "faro-agent-sync-global-"));
  const workspaceRoot = path.join(sandboxRoot, "workspace");
  const codexHome = path.join(sandboxRoot, ".codex");

  await syncGlobalAgentInstructions({
    codexHome,
    skillSource: SKILL_SOURCE,
  });

  const installedSkill = await readFile(
    path.join(codexHome, "skills", "faro-author-paths", "SKILL.md"),
    "utf8",
  );

  assert.equal(installedSkill, SKILL_SOURCE);
  await assert.rejects(readFile(path.join(workspaceRoot, "CLAUDE.md"), "utf8"));
});

test("syncAgentInstructions upserts local artifacts and the global Codex skill", async () => {
  const sandboxRoot = await mkdtemp(path.join(tmpdir(), "faro-agent-sync-"));
  const workspaceRoot = path.join(sandboxRoot, "workspace");
  const codexHome = path.join(sandboxRoot, ".codex");

  await mkdir(path.join(workspaceRoot, "skills", "faro-author-paths"), { recursive: true });
  await mkdir(codexHome, { recursive: true });

  await syncAgentInstructions({
    workspaceRoot,
    codexHome,
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  const claude = await readFile(path.join(workspaceRoot, "CLAUDE.md"), "utf8");
  const copilot = await readFile(
    path.join(workspaceRoot, ".github", "copilot-instructions.md"),
    "utf8",
  );
  const copilotAgent = await readFile(
    path.join(workspaceRoot, ".github", "agents", "faro-path-author.agent.md"),
    "utf8",
  );
  const installedSkill = await readFile(
    path.join(codexHome, "skills", "faro-author-paths", "SKILL.md"),
    "utf8",
  );

  assert.match(claude, /Embedded AGENTS\.md/);
  assert.match(copilot, /Faro Agent Instructions/);
  assert.match(copilotAgent, /name: Faro Path Author/);
  assert.match(copilotAgent, /tools: \['faro\.local\/\*'\]/);
  assert.equal(installedSkill, SKILL_SOURCE);
  await stat(path.join(workspaceRoot, ".github", "agents"));
});

test("syncVsCodeCopilotAgent is idempotent for the Faro custom agent file", async () => {
  const sandboxRoot = await mkdtemp(path.join(tmpdir(), "faro-copilot-agent-"));
  const workspaceRoot = path.join(sandboxRoot, "workspace");

  await syncVsCodeCopilotAgent({
    workspaceRoot,
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  const first = await readFile(
    path.join(workspaceRoot, ".github", "agents", "faro-path-author.agent.md"),
    "utf8",
  );

  await syncVsCodeCopilotAgent({
    workspaceRoot,
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  const second = await readFile(
    path.join(workspaceRoot, ".github", "agents", "faro-path-author.agent.md"),
    "utf8",
  );

  assert.equal(second, first);
});

test("upsertManagedMarkdownSection appends a Faro block without removing existing content", () => {
  const result = upsertManagedMarkdownSection({
    existingContent: "# Existing\n\nKeep this.\n",
    blockId: "CLAUDE",
    content: "Generated Faro guidance.",
  });

  assert.match(result, /# Existing/);
  assert.match(result, /Keep this\./);
  assert.match(result, /<!-- FARO:BEGIN CLAUDE -->/);
  assert.match(result, /Generated Faro guidance\./);
  assert.match(result, /<!-- FARO:END CLAUDE -->/);
});

test("upsertManagedMarkdownSection replaces only the managed Faro block", () => {
  const result = upsertManagedMarkdownSection({
    existingContent: `# Existing

Keep this.

<!-- FARO:BEGIN CLAUDE -->
Old Faro guidance.
<!-- FARO:END CLAUDE -->
`,
    blockId: "CLAUDE",
    content: "New Faro guidance.",
  });

  assert.match(result, /# Existing/);
  assert.match(result, /Keep this\./);
  assert.doesNotMatch(result, /Old Faro guidance\./);
  assert.match(result, /New Faro guidance\./);
});
