import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import {
  buildClaudeInstructions,
  buildCopilotInstructions,
  buildGlobalCopilotInstructions,
  buildVsCodeCopilotAgent,
  syncGlobalAgentInstructions,
  syncAgentInstructions,
  syncLocalAgentInstructions,
  syncVsCodeCopilotAgent,
  upsertManagedMarkdownSection,
} from "../../src/infra/tooling/agent-instruction-sync.ts";

const AGENTS_SOURCE = `# Faro Path Author Agent

Use MCP first.
`;

const SKILL_SOURCE = `---
name: faro-author-paths
---

# Faro Author Paths

Use faro.upsertPath.
`;

test("buildClaudeInstructions embeds both source documents", () => {
  const content = buildClaudeInstructions({
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  assert.match(content, /generated by Faro/);
  assert.match(content, /Embedded AGENTS\.md/);
  assert.match(content, /Embedded SKILL\.md/);
  assert.match(content, /Use MCP first\./);
  assert.match(content, /Use faro\.upsertPath\./);
});

test("buildCopilotInstructions produces a concise repository instruction file", () => {
  const content = buildCopilotInstructions({
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  assert.match(content, /Faro Agent Instructions/);
  assert.match(content, /faro\.listPaths/);
  assert.match(content, /faro\.upsertPath/);
  assert.match(content, /AGENTS\.md remains the source of truth/);
});

test("buildVsCodeCopilotAgent produces a custom agent definition with Faro MCP tools", () => {
  const content = buildVsCodeCopilotAgent({
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  assert.match(content, /^---/);
  assert.match(content, /name: Faro Path Author/);
  assert.match(content, /tools: \['faro\.local\/\*'\]/);
  assert.match(content, /Use the Faro MCP tools to author or revise one temporary comprehension path\./);
  assert.match(content, /Use MCP first\./);
  assert.match(content, /Use faro\.upsertPath\./);
});

test("buildGlobalCopilotInstructions produces a user-level instructions file", () => {
  const content = buildGlobalCopilotInstructions({
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  assert.match(content, /^---/);
  assert.match(content, /name: Faro Global Instructions/);
  assert.match(content, /applyTo: "\*\*"/);
  assert.match(content, /faro\.listPaths/);
  assert.match(content, /Use faro\.upsertPath\./);
});

test("syncLocalAgentInstructions upserts workspace-scoped artifacts including a local Codex skill", async () => {
  const sandboxRoot = await mkdtemp(path.join(tmpdir(), "faro-agent-sync-local-"));
  const workspaceRoot = path.join(sandboxRoot, "workspace");

  await syncLocalAgentInstructions({
    workspaceRoot,
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  const claude = await readFile(path.join(workspaceRoot, "CLAUDE.md"), "utf8");
  const copilot = await readFile(
    path.join(workspaceRoot, ".github", "copilot-instructions.md"),
    "utf8",
  );
  const copilotAgent = await readFile(
    path.join(workspaceRoot, ".github", "agents", "faro-path-author.agent.md"),
    "utf8",
  );
  const localCodexSkill = await readFile(
    path.join(workspaceRoot, ".codex", "skills", "faro-author-paths", "SKILL.md"),
    "utf8",
  );

  assert.match(claude, /Embedded AGENTS\.md/);
  assert.match(copilot, /Faro Agent Instructions/);
  assert.match(copilotAgent, /name: Faro Path Author/);
  assert.equal(localCodexSkill, SKILL_SOURCE);
});

test("syncGlobalAgentInstructions upserts user-level Claude, Copilot, and Codex artifacts", async () => {
  const sandboxRoot = await mkdtemp(path.join(tmpdir(), "faro-agent-sync-global-"));
  const workspaceRoot = path.join(sandboxRoot, "workspace");
  const codexHome = path.join(sandboxRoot, ".codex");
  const claudeHome = path.join(sandboxRoot, ".claude");
  const copilotHome = path.join(sandboxRoot, ".copilot");

  await syncGlobalAgentInstructions({
    codexHome,
    claudeHome,
    copilotHome,
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  const globalClaude = await readFile(path.join(claudeHome, "CLAUDE.md"), "utf8");
  const globalCopilotInstructions = await readFile(
    path.join(copilotHome, "instructions", "faro.instructions.md"),
    "utf8",
  );
  const globalCopilotAgent = await readFile(
    path.join(copilotHome, "agents", "faro-path-author.agent.md"),
    "utf8",
  );
  const installedSkill = await readFile(
    path.join(codexHome, "skills", "faro-author-paths", "SKILL.md"),
    "utf8",
  );

  assert.match(globalClaude, /Embedded AGENTS\.md/);
  assert.match(globalCopilotInstructions, /name: Faro Global Instructions/);
  assert.match(globalCopilotAgent, /name: Faro Path Author/);
  assert.equal(installedSkill, SKILL_SOURCE);
  await assert.rejects(readFile(path.join(workspaceRoot, "CLAUDE.md"), "utf8"));
});

test("syncGlobalAgentInstructions refuses to overwrite an existing Faro Copilot agent without force", async () => {
  const sandboxRoot = await mkdtemp(path.join(tmpdir(), "faro-agent-sync-global-guard-"));
  const codexHome = path.join(sandboxRoot, ".codex");
  const claudeHome = path.join(sandboxRoot, ".claude");
  const copilotHome = path.join(sandboxRoot, ".copilot");
  const existingAgentPath = path.join(copilotHome, "agents", "faro-path-author.agent.md");
  const existingInstructionsPath = path.join(copilotHome, "instructions", "faro.instructions.md");

  await mkdir(path.dirname(existingAgentPath), { recursive: true });
  await mkdir(path.dirname(existingInstructionsPath), { recursive: true });
  await writeFile(existingAgentPath, "custom user agent", "utf8");
  await writeFile(existingInstructionsPath, "custom user instructions", "utf8");

  await assert.rejects(
    syncGlobalAgentInstructions({
      codexHome,
      claudeHome,
      copilotHome,
      agentsSource: AGENTS_SOURCE,
      skillSource: SKILL_SOURCE,
    }),
    /Refusing to overwrite existing Faro global file/,
  );

  assert.equal(await readFile(existingAgentPath, "utf8"), "custom user agent");
  assert.equal(await readFile(existingInstructionsPath, "utf8"), "custom user instructions");
});

test("syncGlobalAgentInstructions overwrites Faro Copilot global files when forced", async () => {
  const sandboxRoot = await mkdtemp(path.join(tmpdir(), "faro-agent-sync-global-force-"));
  const codexHome = path.join(sandboxRoot, ".codex");
  const claudeHome = path.join(sandboxRoot, ".claude");
  const copilotHome = path.join(sandboxRoot, ".copilot");
  const existingAgentPath = path.join(copilotHome, "agents", "faro-path-author.agent.md");
  const existingInstructionsPath = path.join(copilotHome, "instructions", "faro.instructions.md");

  await mkdir(path.dirname(existingAgentPath), { recursive: true });
  await mkdir(path.dirname(existingInstructionsPath), { recursive: true });
  await writeFile(existingAgentPath, "custom user agent", "utf8");
  await writeFile(existingInstructionsPath, "custom user instructions", "utf8");

  await syncGlobalAgentInstructions({
    codexHome,
    claudeHome,
    copilotHome,
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
    force: true,
  });

  assert.match(await readFile(existingAgentPath, "utf8"), /name: Faro Path Author/);
  assert.match(await readFile(existingInstructionsPath, "utf8"), /name: Faro Global Instructions/);
});

test("syncAgentInstructions upserts both local and global artifacts", async () => {
  const sandboxRoot = await mkdtemp(path.join(tmpdir(), "faro-agent-sync-"));
  const workspaceRoot = path.join(sandboxRoot, "workspace");
  const codexHome = path.join(sandboxRoot, ".codex");
  const claudeHome = path.join(sandboxRoot, ".claude");
  const copilotHome = path.join(sandboxRoot, ".copilot");

  await mkdir(path.join(workspaceRoot, "skills", "faro-author-paths"), { recursive: true });
  await mkdir(codexHome, { recursive: true });

  await syncAgentInstructions({
    workspaceRoot,
    codexHome,
    claudeHome,
    copilotHome,
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  const claude = await readFile(path.join(workspaceRoot, "CLAUDE.md"), "utf8");
  const copilot = await readFile(
    path.join(workspaceRoot, ".github", "copilot-instructions.md"),
    "utf8",
  );
  const copilotAgent = await readFile(
    path.join(workspaceRoot, ".github", "agents", "faro-path-author.agent.md"),
    "utf8",
  );
  const localCodexSkill = await readFile(
    path.join(workspaceRoot, ".codex", "skills", "faro-author-paths", "SKILL.md"),
    "utf8",
  );
  const globalClaude = await readFile(path.join(claudeHome, "CLAUDE.md"), "utf8");
  const globalCopilotInstructions = await readFile(
    path.join(copilotHome, "instructions", "faro.instructions.md"),
    "utf8",
  );
  const globalCopilotAgent = await readFile(
    path.join(copilotHome, "agents", "faro-path-author.agent.md"),
    "utf8",
  );
  const installedSkill = await readFile(
    path.join(codexHome, "skills", "faro-author-paths", "SKILL.md"),
    "utf8",
  );

  assert.match(claude, /Embedded AGENTS\.md/);
  assert.match(copilot, /Faro Agent Instructions/);
  assert.match(copilotAgent, /name: Faro Path Author/);
  assert.match(copilotAgent, /tools: \['faro\.local\/\*'\]/);
  assert.equal(localCodexSkill, SKILL_SOURCE);
  assert.match(globalClaude, /Embedded AGENTS\.md/);
  assert.match(globalCopilotInstructions, /name: Faro Global Instructions/);
  assert.match(globalCopilotAgent, /name: Faro Path Author/);
  assert.equal(installedSkill, SKILL_SOURCE);
  await stat(path.join(workspaceRoot, ".github", "agents"));
});

test("syncVsCodeCopilotAgent is idempotent for the Faro custom agent file", async () => {
  const sandboxRoot = await mkdtemp(path.join(tmpdir(), "faro-copilot-agent-"));
  const workspaceRoot = path.join(sandboxRoot, "workspace");

  await syncVsCodeCopilotAgent({
    workspaceRoot,
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  const first = await readFile(
    path.join(workspaceRoot, ".github", "agents", "faro-path-author.agent.md"),
    "utf8",
  );

  await syncVsCodeCopilotAgent({
    workspaceRoot,
    agentsSource: AGENTS_SOURCE,
    skillSource: SKILL_SOURCE,
  });

  const second = await readFile(
    path.join(workspaceRoot, ".github", "agents", "faro-path-author.agent.md"),
    "utf8",
  );

  assert.equal(second, first);
});

test("upsertManagedMarkdownSection appends a Faro block without removing existing content", () => {
  const result = upsertManagedMarkdownSection({
    existingContent: "# Existing\n\nKeep this.\n",
    blockId: "CLAUDE",
    content: "Generated Faro guidance.",
  });

  assert.match(result, /# Existing/);
  assert.match(result, /Keep this\./);
  assert.match(result, /<!-- FARO:BEGIN CLAUDE -->/);
  assert.match(result, /Generated Faro guidance\./);
  assert.match(result, /<!-- FARO:END CLAUDE -->/);
});

test("upsertManagedMarkdownSection replaces only the managed Faro block", () => {
  const result = upsertManagedMarkdownSection({
    existingContent: `# Existing

Keep this.

<!-- FARO:BEGIN CLAUDE -->
Old Faro guidance.
<!-- FARO:END CLAUDE -->
`,
    blockId: "CLAUDE",
    content: "New Faro guidance.",
  });

  assert.match(result, /# Existing/);
  assert.match(result, /Keep this\./);
  assert.doesNotMatch(result, /Old Faro guidance\./);
  assert.match(result, /New Faro guidance\./);
});
