import os from "node:os";
import path from "node:path";
import { mkdir, readFile, writeFile } from "node:fs/promises";

type SyncAgentInstructionsOptions = {
  workspaceRoot: string;
  codexHome?: string;
  agentsSource: string;
  skillSource: string;
};

type InstructionSources = {
  agentsSource: string;
  skillSource: string;
};

export async function syncAgentInstructions({
  workspaceRoot,
  codexHome = path.join(os.homedir(), ".codex"),
  agentsSource,
  skillSource,
}: SyncAgentInstructionsOptions): Promise<void> {
  const claudePath = path.join(workspaceRoot, "CLAUDE.md");
  const copilotPath = path.join(workspaceRoot, ".github", "copilot-instructions.md");
  const codexSkillPath = path.join(codexHome, "skills", "faro-author-paths", "SKILL.md");

  await mkdir(path.dirname(claudePath), { recursive: true });
  await mkdir(path.dirname(copilotPath), { recursive: true });
  await mkdir(path.dirname(codexSkillPath), { recursive: true });

  const claudeExisting = await readOptionalFile(claudePath);
  const copilotExisting = await readOptionalFile(copilotPath);

  await writeFile(
    claudePath,
    upsertManagedMarkdownSection({
      existingContent: claudeExisting,
      blockId: "CLAUDE",
      content: buildClaudeInstructions({
        agentsSource,
        skillSource,
      }),
    }),
    "utf8",
  );
  await writeFile(
    copilotPath,
    upsertManagedMarkdownSection({
      existingContent: copilotExisting,
      blockId: "COPILOT",
      content: buildCopilotInstructions({
        agentsSource,
        skillSource,
      }),
    }),
    "utf8",
  );
  await syncVsCodeCopilotAgent({
    workspaceRoot,
    agentsSource,
    skillSource,
  });
  await writeFile(codexSkillPath, skillSource, "utf8");
}

export function buildClaudeInstructions({
  agentsSource,
  skillSource,
}: InstructionSources): string {
  return `# CLAUDE.md

This file is generated by Faro.
Source files:
- AGENTS.md
- skills/faro-author-paths/SKILL.md

Claude Code should treat AGENTS.md and the Faro skill as the source of truth for authoring Faro paths.
Prefer MCP-driven Faro workflows when the runtime exposes \`faro.*\` operations.

## Embedded AGENTS.md

${agentsSource.trim()}

## Embedded SKILL.md

${skillSource.trim()}
`;
}

export function buildCopilotInstructions({
  agentsSource,
  skillSource,
}: InstructionSources): string {
  return `# Faro Agent Instructions

This file is generated by Faro.
AGENTS.md remains the source of truth for the agent role.
The Faro skill remains the source of truth for authoring behavior.

When GitHub Copilot can access the Faro MCP surface:

1. Start with \`faro.listPaths\`.
2. Use \`faro.getPath\` before revising an existing path.
3. Prefer one \`faro.upsertPath\` whole-path write.
4. Use \`faro.setActivePath\` only when the new path should become primary.
5. Use \`faro.setCurrentBeacon\` only when the starting step should move.

Keep Faro paths linear for the current MVP.
Do not invent a parallel schema.
Do not modify source code just to fit a path.

## AGENTS Summary

${agentsSource.trim()}

## SKILL Summary

${skillSource.trim()}
`;
}

export async function syncVsCodeCopilotAgent({
  workspaceRoot,
  agentsSource,
  skillSource,
}: {
  workspaceRoot: string;
} & InstructionSources): Promise<void> {
  const copilotAgentPath = path.join(
    workspaceRoot,
    ".github",
    "agents",
    "faro-path-author.agent.md",
  );

  await mkdir(path.dirname(copilotAgentPath), { recursive: true });
  await writeFile(
    copilotAgentPath,
    buildVsCodeCopilotAgent({
      agentsSource,
      skillSource,
    }),
    "utf8",
  );
}

export function buildVsCodeCopilotAgent({
  agentsSource,
  skillSource,
}: InstructionSources): string {
  return `---
name: Faro Path Author
description: Use the Faro MCP tools to author or revise one temporary comprehension path.
tools: ['faro.local/*']
---

# Faro Path Author

Use this agent when the goal is to turn code understanding into one clear Faro path for a human reader.

## Operating Rules

- Use the Faro MCP tools before proposing manual JSON edits.
- Keep the path linear for the current MVP.
- Prefer one whole-path \`faro.upsertPath\` write.
- Do not change source code just to fit the path.
- If the runtime is unavailable, still return valid Faro data using the canonical schema.

## AGENTS Source

${agentsSource.trim()}

## SKILL Source

${skillSource.trim()}
`;
}

export function upsertManagedMarkdownSection({
  existingContent,
  blockId,
  content,
}: {
  existingContent: string;
  blockId: string;
  content: string;
}): string {
  const begin = `<!-- FARO:BEGIN ${blockId} -->`;
  const end = `<!-- FARO:END ${blockId} -->`;
  const block = `${begin}\n${content.trim()}\n${end}`;
  const pattern = new RegExp(`${escapeRegExp(begin)}[\\s\\S]*?${escapeRegExp(end)}`, "m");

  if (!existingContent.trim()) {
    return `${block}\n`;
  }

  if (pattern.test(existingContent)) {
    return existingContent.replace(pattern, block);
  }

  return `${existingContent.trimEnd()}\n\n${block}\n`;
}

async function readOptionalFile(filePath: string): Promise<string> {
  try {
    return await readFile(filePath, "utf8");
  } catch {
    return "";
  }
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
